name: Publish

on:
  push:

jobs:
  publish_to_dockerhub:
    name: Publish to DockerHub
    runs-on: ubuntu-latest
    steps:
      - name: "Setup: Check out the repo"
        uses: actions/checkout@v3
      - name: "Setup: Get the branch name for tagging purposes"
        run: |-
          GIT_BRANCH_NAME=$(echo '${{ github.ref_name }}' | sed -e 's|/|-|g')
          echo "GIT_BRANCH_NAME=$GIT_BRANCH_NAME" >> $GITHUB_ENV
      - name: "Setup: Setup QEMU"
        uses: docker/setup-qemu-action@v3
        with:
          platforms: "arm64,arm"
      - name: "Setup: Setup Docker Buildx"
        uses: docker/setup-buildx-action@v2
      - name: "Setup: Log in to Docker Hub"
        uses: docker/login-action@465a07811f14bebb1938fbed4728c6a1ff8901fc
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: "Build: Build and Push Image"
        uses: docker/build-push-action@v4
        with:
          tags: ${{ vars.DOCKERHUB_USERNAME }}/dotnet-nvm:${{ env.GIT_BRANCH_NAME }}
          platforms: linux/amd64,linux/arm64
          push: true
      - name: "Build: Pull image"
        run: docker pull ${{ vars.DOCKERHUB_USERNAME }}/dotnet-nvm:${{ env.GIT_BRANCH_NAME }}
      - name: "Build: Check tools are installed"
        run: |-
          echo "dotnet version: $(docker run --rm ${{ vars.DOCKERHUB_USERNAME }}/dotnet-nvm:${{ env.GIT_BRANCH_NAME }} /bin/bash --login -c 'dotnet --version')"
          echo "nvm version: $(docker run --rm ${{ vars.DOCKERHUB_USERNAME }}/dotnet-nvm:${{ env.GIT_BRANCH_NAME }} /bin/bash --login -c 'nvm --version')"
          echo "node version: $(docker run --rm ${{ vars.DOCKERHUB_USERNAME }}/dotnet-nvm:${{ env.GIT_BRANCH_NAME }} /bin/bash --login -c 'node --version')"
          echo "docker version: $(docker run --rm ${{ vars.DOCKERHUB_USERNAME }}/dotnet-nvm:${{ env.GIT_BRANCH_NAME }} /bin/bash --login -c 'docker --version')"
          echo "docker compose version: $(docker run --rm ${{ vars.DOCKERHUB_USERNAME }}/dotnet-nvm:${{ env.GIT_BRANCH_NAME }} /bin/bash --login -c 'docker compose version')"

      - name: "Latest: Build and Push Image"
        if: github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v4
        with:
          tags: ${{ vars.DOCKERHUB_USERNAME }}/dotnet-nvm:latest
          platforms: linux/amd64,linux/arm64
          push: true
      - name: "Latest: Update Dockerhub description"
        if: github.ref == 'refs/heads/main'
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: ${{ vars.DOCKERHUB_USERNAME }}/dotnet-nvm
