name: Publish Latest

on:
  push:
    branches:
      - main

jobs:
  publish_to_dockerhub:
    name: Publish DockerHub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@465a07811f14bebb1938fbed4728c6a1ff8901fc
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build image
        run: docker build -t dotnet-nvm:latest .
      - name: Check installed tools
        run: docker run --rm dotnet-nvm:latest /bin/bash --login -c "dotnet --version && nvm --version && node --version"
      - name: Tag image
        run: docker tag dotnet-nvm:latest ${{ vars.DOCKERHUB_USERNAME }}/dotnet-nvm:latest
      - name: Publish to Docker Hub
        run: docker push ${{ vars.DOCKERHUB_USERNAME }}/dotnet-nvm:latest
